### PR TITLE
remove withRootElement and withRootLocator (fixes #28)

### LINKED ISSUE #28: Remove withRootElement and withRootLocator
Not needed; leftover from an old design

### PR DESCRIPTION
**Pull request by abocz**
While going through things I also cleaned up some unused imports

### CODE REVIEW

**Comment by alechenninger** [comment]
Hrm we may want to remove nested transitions entirely since they might not make any sense without those API's. With this PR leaving it is broken because it doesn't use the root locator.

**Comment by alechenninger** [comment]
@abocz Are you interested in updating this PR? Let me know if you have any questions, no rush

**Comment by alechenninger** [comment]
Looks good! Can you bump the version to 0.2.1 also?

If you're interested, there will be a lot of code to remove from darcy-webdriver as well now that this feature doesn't need to be supported

**Comment by abocz** [comment]
>If you're interested, there will be a lot of code to remove from darcy-webdriver as well now that this feature doesn't need to be supported

Sure, I can take a whack at it.

**Comment by alechenninger** [comment]
Thanks!

**Pull request merged**
